---
title: "eds212-day2-tasks"
format: html
---

library(tidyverse)
install.packages("palmerpenguins")
library(palmerpenguins)
data(package = 'palmerpenguins')
penguins <- penguins

usethis::use_git()
usethis::use_github()

# Section 2: find derivative expression and slope
```{r}
# find slope of f(x) = x^2 at x = 3

dc_dx <- D(expr = expression(x^2), name = "x")
dc_dx


remove( "dc_dt_fun")

x <- 3

eval(dc_dx)

```


```{r}
# slope of P(a) = 2* (3a+2)^4 - 5. at 1.2

dc_da <- D(expr = expression(2*(3*a+2)^4 -5), name = "a")
dc_da

a <- 1.2

eval(dc_da)
```

# Section 3: Make another penguin plot


```{r}

# first scatter plot of penguins 

library(palmerpenguins)
head(penguins)
data(package = 'palmerpenguins')
penguins <- penguins
 
library (ggplot2)

ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = species)) + 
  geom_point() +
  labs(tittle = "penguin bill sizes by species",
       x = "bill length (mm)", y = "bill depth (mm)")
    
```


```{r}
# Jitter plot 

penguins <- penguins
ggplot(data = penguins, aes(x = species, y = flipper_length_mm))+
       geom_jitter() +
  labs(tittle = "penguin bill sizes by species",
       x = "species", y = "flipper length")

```





